<a href="https://colab.research.google.com/github/hyosungHWANG/201927151_hyosung/blob/main/2024_01_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [96]:
import pandas as pd

df = pd.read_excel('BoxOffice.xlsx')

df

print(df.info())
print(df['대표국적'].value_counts())
print(df[df['대표국적'] == '영국'])
print(df.groupby('대표국적').min())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   순위      200 non-null    int64
 1   영화명     200 non-null    object
 2   개봉일     200 non-null    datetime64[ns]
 3   매출액     200 non-null    int64
 4   관객수     200 non-null    int64
 5   스크린수    200 non-null    int64
 6   상영횟수    200 non-null    int64
 7   대표국적    200 non-null    object
 8   국적      200 non-null    object
 9   배급사     200 non-null    object
dtypes: datetime64[ns](1), int64(5), object(4)
memory usage: 15.8+ KB
None
한국    116
미국     82
일본      1
영국      1
Name: 대표국적, dtype: int64
      순위     영화명        개봉일          매출액      관객수  스크린수   상영횟수 대표국적  국적  \
194  195  어바웃 타임 2013-12-05  25312684300  3449451   568  67267   영국  영국

                     배급사
194  유니버설픽쳐스인터내셔널 코리아(유)
       순위        개봉일          매출액      관객수  스크린수   상영횟수  국적  \
대표국적
미국      5 2005-12-01  21476688172  3379762   319  38456  미국
영국    195 2013-12-05  25312684300  3449451   568  67267  영국
일본    172 2017-01-04  30628194346  3793790   947  88917  일본
한국      1 2005-01-27  22209675300  3389125   238  47155  한국

                         배급사
대표국적
미국    (주)디스테이션,워너브러더스 코리아(주)
영국       유니버설픽쳐스인터내셔널 코리아(유)
일본             메가박스중앙(주)플러스엠
한국       (주)넥스트엔터테인먼트월드(NEW)

<ipython-input-96-155315a635cd>:10: FutureWarning: Dropping invalid columns in DataFrameGroupBy.min is deprecated. In a future version, a TypeError will be raised. Before calling .min, select only columns which should be valid for the function.
  print(df.groupby('대표국적').min())

In [71]:
import pandas as pd

df = pd.read_excel('data.xlsx')
print(df)

df_1 = df.replace(0,7)

    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
1  B반  김이정  여  78.0   45.0   응시   확인
2  A반  오지수  남   NaN    NaN   응시   확인
3  B반  김선후  남  33.0   44.0   응시  NaN
4  A반  하진희  여   0.0   85.0   응시  NaN
5  A반  강현진  남   NaN    NaN  NaN  NaN
6  B반  김진솔  남  90.0   89.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
8  A반  김성희  남   NaN    NaN  NaN   확인
9  B반  이지서  여  86.0  100.0   응시   확인

In [70]:
import pandas as pd

df = pd.read_excel('data.xlsx')
print(df)

df.drop('확인여부',axis=1)

    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
1  B반  김이정  여  78.0   45.0   응시   확인
2  A반  오지수  남   NaN    NaN   응시   확인
3  B반  김선후  남  33.0   44.0   응시  NaN
4  A반  하진희  여   0.0   85.0   응시  NaN
5  A반  강현진  남   NaN    NaN  NaN  NaN
6  B반  김진솔  남  90.0   89.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
8  A반  김성희  남   NaN    NaN  NaN   확인
9  B반  이지서  여  86.0  100.0   응시   확인

    반   이름 성별    국어     수학 응시여부
0  A반  구이서  남  90.0   89.0   응시
1  B반  김이정  여  78.0   45.0   응시
2  A반  오지수  남   NaN    NaN   응시
3  B반  김선후  남  33.0   44.0   응시
4  A반  하진희  여   0.0   85.0   응시
5  A반  강현진  남   NaN    NaN  NaN
6  B반  김진솔  남  90.0   89.0   응시
7  B반  박서준  여  78.0   45.0   응시
8  A반  김성희  남   NaN    NaN  NaN
9  B반  이지서  여  86.0  100.0   응시

In [66]:
import pandas as pd

df = pd.read_excel('data.xlsx')
print(df)

df['총점'] = df['국어'] + df['수학'] #새 칼럼 추가
df

    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
1  B반  김이정  여  78.0   45.0   응시   확인
2  A반  오지수  남   NaN    NaN   응시   확인
3  B반  김선후  남  33.0   44.0   응시  NaN
4  A반  하진희  여   0.0   85.0   응시  NaN
5  A반  강현진  남   NaN    NaN  NaN  NaN
6  B반  김진솔  남  90.0   89.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
8  A반  김성희  남   NaN    NaN  NaN   확인
9  B반  이지서  여  86.0  100.0   응시   확인

    반   이름 성별    국어     수학 응시여부 확인여부     총점
0  A반  구이서  남  90.0   89.0   응시   확인  179.0
1  B반  김이정  여  78.0   45.0   응시   확인  123.0
2  A반  오지수  남   NaN    NaN   응시   확인    NaN
3  B반  김선후  남  33.0   44.0   응시  NaN   77.0
4  A반  하진희  여   0.0   85.0   응시  NaN   85.0
5  A반  강현진  남   NaN    NaN  NaN  NaN    NaN
6  B반  김진솔  남  90.0   89.0   응시   확인  179.0
7  B반  박서준  여  78.0   45.0   응시   확인  123.0
8  A반  김성희  남   NaN    NaN  NaN   확인    NaN
9  B반  이지서  여  86.0  100.0   응시   확인  186.0

In [65]:
import pandas as pd

df = pd.read_excel('data.xlsx')
print(df)

df2=df.dropna(subset=['국어'])
df2

    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
1  B반  김이정  여  78.0   45.0   응시   확인
2  A반  오지수  남   NaN    NaN   응시   확인
3  B반  김선후  남  33.0   44.0   응시  NaN
4  A반  하진희  여   0.0   85.0   응시  NaN
5  A반  강현진  남   NaN    NaN  NaN  NaN
6  B반  김진솔  남  90.0   89.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
8  A반  김성희  남   NaN    NaN  NaN   확인
9  B반  이지서  여  86.0  100.0   응시   확인

    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
1  B반  김이정  여  78.0   45.0   응시   확인
3  B반  김선후  남  33.0   44.0   응시  NaN
4  A반  하진희  여   0.0   85.0   응시  NaN
6  B반  김진솔  남  90.0   89.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
9  B반  이지서  여  86.0  100.0   응시   확인

In [64]:
import pandas as pd

df = pd.read_excel('data.xlsx')
print(df)

#df_1 = df.fillna({'확인여부':'완료'})
df_1 = df.fillna(0)

print(df_1)

    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
1  B반  김이정  여  78.0   45.0   응시   확인
2  A반  오지수  남   NaN    NaN   응시   확인
3  B반  김선후  남  33.0   44.0   응시  NaN
4  A반  하진희  여   0.0   85.0   응시  NaN
5  A반  강현진  남   NaN    NaN  NaN  NaN
6  B반  김진솔  남  90.0   89.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
8  A반  김성희  남   NaN    NaN  NaN   확인
9  B반  이지서  여  86.0  100.0   응시   확인
    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
1  B반  김이정  여  78.0   45.0   응시   확인
2  A반  오지수  남   0.0    0.0   응시   확인
3  B반  김선후  남  33.0   44.0   응시    0
4  A반  하진희  여   0.0   85.0   응시    0
5  A반  강현진  남   0.0    0.0    0    0
6  B반  김진솔  남  90.0   89.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
8  A반  김성희  남   0.0    0.0    0   확인
9  B반  이지서  여  86.0  100.0   응시   확인

In [57]:
import pandas as pd

df = pd.read_excel('data.xlsx')
print(df)

print(df.isna())
print(df.isna().sum())

    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
1  B반  김이정  여  78.0   45.0   응시   확인
2  A반  오지수  남   NaN    NaN   응시   확인
3  B반  김선후  남  33.0   44.0   응시  NaN
4  A반  하진희  여   0.0   85.0   응시  NaN
5  A반  강현진  남   NaN    NaN  NaN  NaN
6  B반  김진솔  남  90.0   89.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
8  A반  김성희  남   NaN    NaN  NaN   확인
9  B반  이지서  여  86.0  100.0   응시   확인
       반     이름     성별     국어     수학   응시여부   확인여부
0  False  False  False  False  False  False  False
1  False  False  False  False  False  False  False
2  False  False  False   True   True  False  False
3  False  False  False  False  False  False   True
4  False  False  False  False  False  False   True
5  False  False  False   True   True   True   True
6  False  False  False  False  False  False  False
7  False  False  False  False  False  False  False
8  False  False  False   True   True   True  False
9  False  False  False  False  False  False  False
반       0
이름      0
성별      0
국어      3
수학      3
응시여부    2
확인여부    3
dtype: int64

In [54]:
import pandas as pd

df = pd.read_excel('data.xlsx')
print(df)

print(df.groupby('반').sum())
print(df.groupby('반').mean())

    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
1  B반  김이정  여  78.0   45.0   응시   확인
2  A반  오지수  남   NaN    NaN   응시   확인
3  B반  김선후  남  33.0   44.0   응시  NaN
4  A반  하진희  여   0.0   85.0   응시  NaN
5  A반  강현진  남   NaN    NaN  NaN  NaN
6  B반  김진솔  남  90.0   89.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
8  A반  김성희  남   NaN    NaN  NaN   확인
9  B반  이지서  여  86.0  100.0   응시   확인
       국어     수학
반
A반   90.0  174.0
B반  365.0  323.0
      국어    수학
반
A반  45.0  87.0
B반  73.0  64.6

<ipython-input-54-3edde4a98d79>:6: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  print(df.groupby('반').sum())
<ipython-input-54-3edde4a98d79>:7: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  print(df.groupby('반').mean())

In [53]:
import pandas as pd

df = pd.read_excel('data.xlsx')
print(df)

print(df['국어'].sum())
print(df['국어'].mean())

    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
1  B반  김이정  여  78.0   45.0   응시   확인
2  A반  오지수  남   NaN    NaN   응시   확인
3  B반  김선후  남  33.0   44.0   응시  NaN
4  A반  하진희  여   0.0   85.0   응시  NaN
5  A반  강현진  남   NaN    NaN  NaN  NaN
6  B반  김진솔  남  90.0   89.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
8  A반  김성희  남   NaN    NaN  NaN   확인
9  B반  이지서  여  86.0  100.0   응시   확인
455.0
65.0

In [51]:
import pandas as pd

df = pd.read_excel('data.xlsx')
print(df)

print(df.index)
print(df.columns)
print(df.size)

    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
1  B반  김이정  여  78.0   45.0   응시   확인
2  A반  오지수  남   NaN    NaN   응시   확인
3  B반  김선후  남  33.0   44.0   응시  NaN
4  A반  하진희  여   0.0   85.0   응시  NaN
5  A반  강현진  남   NaN    NaN  NaN  NaN
6  B반  김진솔  남  90.0   89.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
8  A반  김성희  남   NaN    NaN  NaN   확인
9  B반  이지서  여  86.0  100.0   응시   확인
RangeIndex(start=0, stop=10, step=1)
Index(['반', '이름', '성별', '국어', '수학', '응시여부', '확인여부'], dtype='object')
70

In [48]:
import pandas as pd

df = pd.read_excel('data.xlsx')
print(df)

print(df.sort_values(by=['이름'])) #ㄱ,ㄴ,ㄷ순서 정렬 => 오름차순(=ascending)
print(df.sort_values(by=['국어'],ascending=False)) #국어 점수 기준 내림차순 정렬

    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
1  B반  김이정  여  78.0   45.0   응시   확인
2  A반  오지수  남   NaN    NaN   응시   확인
3  B반  김선후  남  33.0   44.0   응시  NaN
4  A반  하진희  여   0.0   85.0   응시  NaN
5  A반  강현진  남   NaN    NaN  NaN  NaN
6  B반  김진솔  남  90.0   89.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
8  A반  김성희  남   NaN    NaN  NaN   확인
9  B반  이지서  여  86.0  100.0   응시   확인
    반   이름 성별    국어     수학 응시여부 확인여부
5  A반  강현진  남   NaN    NaN  NaN  NaN
0  A반  구이서  남  90.0   89.0   응시   확인
3  B반  김선후  남  33.0   44.0   응시  NaN
8  A반  김성희  남   NaN    NaN  NaN   확인
1  B반  김이정  여  78.0   45.0   응시   확인
6  B반  김진솔  남  90.0   89.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
2  A반  오지수  남   NaN    NaN   응시   확인
9  B반  이지서  여  86.0  100.0   응시   확인
4  A반  하진희  여   0.0   85.0   응시  NaN
    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
6  B반  김진솔  남  90.0   89.0   응시   확인
9  B반  이지서  여  86.0  100.0   응시   확인
1  B반  김이정  여  78.0   45.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
3  B반  김선후  남  33.0   44.0   응시  NaN
4  A반  하진희  여   0.0   85.0   응시  NaN
2  A반  오지수  남   NaN    NaN   응시   확인
5  A반  강현진  남   NaN    NaN  NaN  NaN
8  A반  김성희  남   NaN    NaN  NaN   확인

In [45]:
import pandas as pd

df = pd.read_excel('data.xlsx')
print(df)

print(df[(df['국어']>=80) & (df['수학']>=90)]) # &는 and 연산자
print(df[(df['국어']>=80) | (df['수학']>=90)]) # |는 or 연산자

    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
1  B반  김이정  여  78.0   45.0   응시   확인
2  A반  오지수  남   NaN    NaN   응시   확인
3  B반  김선후  남  33.0   44.0   응시  NaN
4  A반  하진희  여   0.0   85.0   응시  NaN
5  A반  강현진  남   NaN    NaN  NaN  NaN
6  B반  김진솔  남  90.0   89.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
8  A반  김성희  남   NaN    NaN  NaN   확인
9  B반  이지서  여  86.0  100.0   응시   확인
    반   이름 성별    국어     수학 응시여부 확인여부
9  B반  이지서  여  86.0  100.0   응시   확인
    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
6  B반  김진솔  남  90.0   89.0   응시   확인
9  B반  이지서  여  86.0  100.0   응시   확인

In [38]:
import pandas as pd

df = pd.read_excel('data.xlsx')
print(df)

print(df['국어'] >= 80)

    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
1  B반  김이정  여  78.0   45.0   응시   확인
2  A반  오지수  남   NaN    NaN   응시   확인
3  B반  김선후  남  33.0   44.0   응시  NaN
4  A반  하진희  여   0.0   85.0   응시  NaN
5  A반  강현진  남   NaN    NaN  NaN  NaN
6  B반  김진솔  남  90.0   89.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
8  A반  김성희  남   NaN    NaN  NaN   확인
9  B반  이지서  여  86.0  100.0   응시   확인
0     True
1    False
2    False
3    False
4    False
5    False
6     True
7    False
8    False
9     True
Name: 국어, dtype: bool

In [37]:
import pandas as pd

df = pd.read_excel('data.xlsx')
print(df)

print(df.loc[2]) #location, 2는 행번호 의미
#print(df.loc[0:3]) #특이하게 loc는 stop을 포함
print(df.iloc[2])
#print(df.iloc[0:3,0:2]) #iloc은 stop미포함

    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
1  B반  김이정  여  78.0   45.0   응시   확인
2  A반  오지수  남   NaN    NaN   응시   확인
3  B반  김선후  남  33.0   44.0   응시  NaN
4  A반  하진희  여   0.0   85.0   응시  NaN
5  A반  강현진  남   NaN    NaN  NaN  NaN
6  B반  김진솔  남  90.0   89.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
8  A반  김성희  남   NaN    NaN  NaN   확인
9  B반  이지서  여  86.0  100.0   응시   확인
반        A반
이름      오지수
성별        남
국어      NaN
수학      NaN
응시여부     응시
확인여부     확인
Name: 2, dtype: object
반        A반
이름      오지수
성별        남
국어      NaN
수학      NaN
응시여부     응시
확인여부     확인
Name: 2, dtype: object

In [27]:
import pandas as pd

df = pd.read_excel('data.xlsx')
print(df)

print(df[0:3]) #종료 행 번호 이전까지 가져옴
print(df['이름'][0:3])

    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
1  B반  김이정  여  78.0   45.0   응시   확인
2  A반  오지수  남   NaN    NaN   응시   확인
3  B반  김선후  남  33.0   44.0   응시  NaN
4  A반  하진희  여   0.0   85.0   응시  NaN
5  A반  강현진  남   NaN    NaN  NaN  NaN
6  B반  김진솔  남  90.0   89.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
8  A반  김성희  남   NaN    NaN  NaN   확인
9  B반  이지서  여  86.0  100.0   응시   확인
    반   이름 성별    국어    수학 응시여부 확인여부
0  A반  구이서  남  90.0  89.0   응시   확인
1  B반  김이정  여  78.0  45.0   응시   확인
2  A반  오지수  남   NaN   NaN   응시   확인
0    구이서
1    김이정
2    오지수
Name: 이름, dtype: object

In [25]:
import pandas as pd

df = pd.read_excel('data.xlsx')
print(df)

print(df['이름']) #데이터프레임['칼럼명']
print(df[['이름', '성별']]) #여러 개 가져올 시 []추가 필요

    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
1  B반  김이정  여  78.0   45.0   응시   확인
2  A반  오지수  남   NaN    NaN   응시   확인
3  B반  김선후  남  33.0   44.0   응시  NaN
4  A반  하진희  여   0.0   85.0   응시  NaN
5  A반  강현진  남   NaN    NaN  NaN  NaN
6  B반  김진솔  남  90.0   89.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
8  A반  김성희  남   NaN    NaN  NaN   확인
9  B반  이지서  여  86.0  100.0   응시   확인
0    구이서
1    김이정
2    오지수
3    김선후
4    하진희
5    강현진
6    김진솔
7    박서준
8    김성희
9    이지서
Name: 이름, dtype: object
    이름 성별
0  구이서  남
1  김이정  여
2  오지수  남
3  김선후  남
4  하진희  여
5  강현진  남
6  김진솔  남
7  박서준  여
8  김성희  남
9  이지서  여

In [21]:
import pandas as pd

df = pd.read_excel('data.xlsx')
print(df)

#print(df.head()) #숫자 생략 시 기본 5개
#print(df.tail(3))
print(df.info())
#rangeindex 전체 몇 행인지, 행의 개수
#data columns 전체 몇 열 인지, 열의 개수
#non-null count 결측치(=비어있다)가 있다면 non-null(비결측치) 숫자 감소
#dtypes은 데이터의 자료형 반환 : 국어,수학 => float형 그외 object

    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
1  B반  김이정  여  78.0   45.0   응시   확인
2  A반  오지수  남   NaN    NaN   응시   확인
3  B반  김선후  남  33.0   44.0   응시  NaN
4  A반  하진희  여   0.0   85.0   응시  NaN
5  A반  강현진  남   NaN    NaN  NaN  NaN
6  B반  김진솔  남  90.0   89.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
8  A반  김성희  남   NaN    NaN  NaN   확인
9  B반  이지서  여  86.0  100.0   응시   확인
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   반       10 non-null     object
 1   이름      10 non-null     object
 2   성별      10 non-null     object
 3   국어      7 non-null      float64
 4   수학      7 non-null      float64
 5   응시여부    8 non-null      object
 6   확인여부    7 non-null      object
dtypes: float64(2), object(5)
memory usage: 688.0+ bytes
None

In [ ]:
import pandas as pd

# 1. data.csv 파일을 읽어서 데이터프레임 생성
# 예시 파일은 제공되지 않았으므로, 대신 주어진 URL에서 데이터를 로드합니다.
url = 'https://raw.githubusercontent.com/Datamanim/pandas/main/lol.csv'

# 2. 데이터를 로드
df = pd.read_csv(url, delimiter='\t')

# 데이터프레임 확인
print(df)

           gameId   creationTime  gameDuration  seasonId  winner  firstBlood  \
0      3326086514  1504279457970          1949         9       1           2
1      3229566029  1497848803862          1851         9       1           1
2      3327363504  1504360103310          1493         9       1           2
3      3326856598  1504348503996          1758         9       1           1
4      3330080762  1504554410899          2094         9       1           2
...           ...            ...           ...       ...     ...         ...
51485  3308904636  1503076540231          1944         9       2           1
51486  3215685759  1496957179355          3304         9       2           1
51487  3322765040  1504029863961          2156         9       2           2
51488  3256675373  1499562036246          1475         9       2           2
51489  3317333020  1503612754059          1445         9       1           1

       firstTower  firstInhibitor  firstBaron  firstDragon  ...  \
0               1               1           1            1  ...
1               1               1           0            1  ...
2               1               1           1            2  ...
3               1               1           1            1  ...
4               1               1           1            1  ...
...           ...             ...         ...          ...  ...
51485           2               2           0            2  ...
51486           1               2           2            2  ...
51487           2               2           0            1  ...
51488           2               2           0            2  ...
51489           1               1           1            2  ...

       t2_towerKills  t2_inhibitorKills  t2_baronKills  t2_dragonKills  \
0                  5                  0              0               1
1                  2                  0              0               0
2                  2                  0              0               1
3                  0                  0              0               0
4                  3                  0              0               1
...              ...                ...            ...             ...
51485             10                  2              0               4
51486             11                  7              4               4
51487             10                  2              0               2
51488             11                  3              0               1
51489              1                  0              0               1

       t2_riftHeraldKills  t2_ban1  t2_ban2  t2_ban3  t2_ban4  t2_ban5
0                       1      114       67       43       16       51
1                       0       11       67      238       51      420
2                       0      157      238      121       57       28
3                       0      164       18      141       40       51
4                       0       86       11      201      122       18
...                   ...      ...      ...      ...      ...      ...
51485                   0       55       -1       90      238      157
51486                   1      157       55      119      154      105
51487                   0      113      122       53       11      157
51488                   0      154       39       51       90      114
51489                   0       11      157      141       31       18

[51490 rows x 61 columns]

In [ ]:
import pandas as pd

df = pd.read_csv('data.csv')
df

   name   age   score
0   Kim    27      92
1   Lee    33      98
2  Park    19      87

In [ ]:
import pandas as pd
df = pd.DataFrame({'name':['Kim','Lee','Park'],
                    'age':[27, 33,19],
                  'score':[92,98,87]}) #key는 column 명으로 지정됨
df

   name  age  score
0   Kim   27     92
1   Lee   33     98
2  Park   19     87

In [ ]:
import pandas as pd
df = pd.DataFrame([ ['Kim',27,92],
                    ['Lee', 33,98],
                    ['Park',19, 87] ])
df

      0   1   2
0   Kim  27  92
1   Lee  33  98
2  Park  19  87

In [ ]:
a = int(input())
output = list()

for i in range(a):
  b = input()
  c = b.split('.')
  if c[-1] == 'jpg' or c[-1] == 'png':
    output.append(b)

print(output)

3
bravo.jpg
bravo.png
alpha.hwp
['bravo.jpg', 'bravo.png']